version: "3.8"

services:
  graduation:
    image: graduation-be:latest
    container_name: graduation-be
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
