# Generated by Django 5.1 on 2024-11-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("key", models.CharField(max_length=128, verbose_name="Key")),
                ("name", models.CharField(blank=True, max_length=128, null=True)),
                ("email", models.EmailField(blank=True, max_length=128, null=True)),
                (
                    "img_url",
                    models.URLField(
                        blank=True, max_length=256, null=True, verbose_name="Img Url"
                    ),
                ),
                ("wisher", models.CharField(blank=True, max_length=1028, null=True)),
                (
                    "confirm",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "yes"), ("no", "no"), ("unknown", "unknown")],
                        default="yes",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active?"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
