# Generated by Django 5.1 on 2024-11-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_example", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wisher",
            name="relationship",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
